export const OPENING_CASH_BALANCE = 5100;
export const CASH_DENOMINATIONS = [500, 200, 100, 50, 20, 10, 5, 2, 1];
export const DEFAULT_DENOMINATION_STATE = Object.fromEntries(
  CASH_DENOMINATIONS.map(d => [d, ''])
);

export const EXPENSE_CATEGORIES = [
  'Groceries & Dairy', 'Staff-Expense', 'Petrol', 'Maintenance',
  'Advertisement', 'Salary', 'Stationary', 'Freight', 'Other'
];

export const OUTLETS = ['FREEGANJ', 'NANAKHEDA'];
export const DEFAULT_LEGACY_OUTLET = 'NANAKHEDA';
export const OUTLET_STORAGE_KEY = 'dsr_selected_outlet';

export const INVENTORY_CATEGORIES = [
  { code: 'A', name: 'Base' },
  { code: 'B', name: 'Dips & Sauces' },
  { code: 'C', name: 'Toppings' },
  { code: 'D', name: 'Cheese' },
  { code: 'E', name: 'Seasonings & Ketchups' },
  { code: 'F', name: 'Side Orders' },
  { code: 'G', name: 'Boxes and Papers' },
  { code: 'H', name: 'Other Essentials' },
  { code: 'I', name: 'Beverages' }
];

export const INVENTORY_UOMS = ['/KG', '/PKT', '/TIN', '/BTL', '/NOS'];

export const DEFAULT_INVENTORY_ITEMS = [
  { "id": "item_1", "name": "Maida (1X50kg)", "category": "Base", "categoryCode": "A", "uom": "/KG", "netPrice": 40.0 },
  { "id": "item_2", "name": "Dough Pouch (1X6X1.8kg)", "category": "Base", "categoryCode": "A", "uom": "/KG", "netPrice": 752.5 },
  { "id": "item_3", "name": "Soyabean Oil (1X13.6kg)", "category": "Base", "categoryCode": "A", "uom": "/KG", "netPrice": 110.3 },
  { "id": "item_4", "name": "Cheese Blend (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 200.48 },
  { "id": "item_5", "name": "English Gauda Cheese (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 227.36 },
  { "id": "item_6", "name": "African Peri Peri (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 252.0 },
  { "id": "item_7", "name": "Hot Chilli Garlic Dip (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 163.52 },
  { "id": "item_8", "name": "Jalapeno Dip (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 191.52 },
  { "id": "item_9", "name": "Makhani Gravy (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 217.28 },
  { "id": "item_10", "name": "Pesto Basil Mayonnaise (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 252.0 },
  { "id": "item_11", "name": "Mexican Salsa (1X12)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 114.24 },
  { "id": "item_12", "name": "Pizza & Pasta Sauce (1X8X1.5kg)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 217.28 },
  { "id": "item_13", "name": "Jain Pizza & Pasta Sauce (1X8X1.5kg)", "category": "Dips & Sauces", "categoryCode": "B", "uom": "/PKT", "netPrice": 173.6 },
  { "id": "item_14", "name": "Jalapeno Tin (1X6)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 330.4 },
  { "id": "item_15", "name": "Mushroom Tin (1X24)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 93.0 },
  { "id": "item_16", "name": "Pineapple Tin (1X24)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 93.45 },
  { "id": "item_17", "name": "Baby Corn (1X24)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 105.0 },
  { "id": "item_18", "name": "Black Olives (1X6)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 580.16 },
  { "id": "item_19", "name": "Red Peprika (1X6)", "category": "Toppings", "categoryCode": "C", "uom": "/TIN", "netPrice": 459.2 },
  { "id": "item_20", "name": "Sweet Corn", "category": "Toppings", "categoryCode": "C", "uom": "/PKT", "netPrice": 75.0 },
  { "id": "item_21", "name": "Tomatoes", "category": "Toppings", "categoryCode": "C", "uom": "/KG", "netPrice": 40.0 },
  { "id": "item_22", "name": "Capsicum", "category": "Toppings", "categoryCode": "C", "uom": "/KG", "netPrice": 80.0 },
  { "id": "item_23", "name": "Onion", "category": "Toppings", "categoryCode": "C", "uom": "/KG", "netPrice": 40.0 },
  { "id": "item_24", "name": "Paneer", "category": "Toppings", "categoryCode": "C", "uom": "/KG", "netPrice": 320.0 },
  { "id": "item_25", "name": "Mozzarella (1X6X2kg)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 940.8 },
  { "id": "item_26", "name": "Cheddar (1X6X2kg)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 1019.2 },
  { "id": "item_27", "name": "Colby (1X6X2kg)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 1299.2 },
  { "id": "item_28", "name": "Monterey (1X6X2kg)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 1299.2 },
  { "id": "item_29", "name": "Orange Cheddar (1X6X2kg)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 1299.2 },
  { "id": "item_30", "name": "Premium Cheese Sauce Burst (1X24)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 201.6 },
  { "id": "item_31", "name": "White Melted Cheese Burst (1X24)", "category": "Cheese", "categoryCode": "D", "uom": "/PKT", "netPrice": 199.36 },
  { "id": "item_32", "name": "Paneer Marinade Seasoning", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/KG", "netPrice": 492.8 },
  { "id": "item_33", "name": "Garlic Bread Seasoning", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/KG", "netPrice": 492.8 },
  { "id": "item_34", "name": "Chilli Flakes Pouch (1kg)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 429.45 },
  { "id": "item_35", "name": "Chilli Flakes Sachet (1X12X500)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 410.0 },
  { "id": "item_36", "name": "Oregano Spice Mix Pouch (1kg)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 588.0 },
  { "id": "item_37", "name": "Oregano Spice Mix Sachet (1X12X500)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 475.0 },
  { "id": "item_38", "name": "Tomato Ketchup Pouch (1X12X950gm)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 88.3 },
  { "id": "item_39", "name": "Tomato Ketchup Sachet (1X6X500X8gm)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 149.7067 },
  { "id": "item_40", "name": "Mustard Sauce (1X12X0.75kg)", "category": "Seasonings & Ketchups", "categoryCode": "E", "uom": "/PKT", "netPrice": 86.24 },
  { "id": "item_41", "name": "Tortilla Wrap Medium Quesadillas (1X12)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 147.0 },
  { "id": "item_42", "name": "Tortilla Wrap Small Quesadillas(1X24)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 67.2 },
  { "id": "item_43", "name": "Flaky Parantha Tacos (1X10)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 228.0 },
  { "id": "item_44", "name": "Pasta Fusilli (1X24)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 72.8 },
  { "id": "item_45", "name": "Pasta Macaroni (1X24)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 72.8 },
  { "id": "item_46", "name": "Lasagne (1X24X500gm)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 147.84 },
  { "id": "item_47", "name": "Spaghetti (1X24X500gm)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 80.64 },
  { "id": "item_48", "name": "K-Cuisine Oil (1X40)", "category": "Side Orders", "categoryCode": "F", "uom": "/BTL", "netPrice": 245.7 },
  { "id": "item_49", "name": "Eggless Choco LavaCake Premix (kg)", "category": "Side Orders", "categoryCode": "F", "uom": "/KG", "netPrice": 288.75 },
  { "id": "item_50", "name": "Eggless RedVelvet LavaCake Premix (kg)", "category": "Side Orders", "categoryCode": "F", "uom": "/KG", "netPrice": 308.7 },
  { "id": "item_51", "name": "Chocolate Syrup (1X12)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 0.0 },
  { "id": "item_52", "name": "Butter Yummy (500gm)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 75.0 },
  { "id": "item_53", "name": "Rich Cream (1lit)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 211.0 },
  { "id": "item_54", "name": "Milk Tetrapack (1lit)", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 75.0 },
  { "id": "item_55", "name": "Dark Choco Compound COD15", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 0.0 },
  { "id": "item_56", "name": "Garlic Bread", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 55.0 },
  { "id": "item_57", "name": "Bread Crumbs", "category": "Side Orders", "categoryCode": "F", "uom": "/PKT", "netPrice": 0.0 },
  { "id": "item_58", "name": "7'' inch Regular Box (1X100)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 9.15 },
  { "id": "item_59", "name": "10'' inch Medium Box (1X50)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 18.88 },
  { "id": "item_60", "name": "13'' inch Large Box (1X50)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 23.01 },
  { "id": "item_61", "name": "18'' inch Giant Box (1X25)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 44.84 },
  { "id": "item_62", "name": "24'' inch Monster Box (1x15)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 89.68 },
  { "id": "item_63", "name": "Lunch Meal Regular Tray (1X50)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_64", "name": "Lunch Meal Medium Tray (1X50)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_65", "name": "Garlic Bread Box (1X200)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 8.56 },
  { "id": "item_66", "name": "Slice Box (1X200)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 9.15 },
  { "id": "item_67", "name": "Pasta Paper Sleeve (1X200)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 5.31 },
  { "id": "item_68", "name": "Pasta Paper Bowl (1X50)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 8.14 },
  { "id": "item_69", "name": "Pasta Aluminium Container (1X100)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_70", "name": "Choco Lava Box (1X200)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 5.02 },
  { "id": "item_71", "name": "Lava Cake Cups (1x140)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 6.96 },
  { "id": "item_72", "name": "Slice Tray (1X200)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 3.19 },
  { "id": "item_73", "name": "Paper Dip Pods (1X100)", "category": "Boxes and Papers", "categoryCode": "G", "uom": "/NOS", "netPrice": 2.66 },
  { "id": "item_74", "name": "Pizza Stool (1X200)", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 296.0 },
  { "id": "item_75", "name": "Wrapping Roll & Foil", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 0.0 },
  { "id": "item_76", "name": "Spoon (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 45.0 },
  { "id": "item_77", "name": "Fork (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 48.0 },
  { "id": "item_78", "name": "Tissue (1X100)", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 36.58 },
  { "id": "item_79", "name": "Cello Tape (1X12)", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_80", "name": "Garbage Bag Small", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 30.0 },
  { "id": "item_81", "name": "Garbage Bag Large", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 70.0 },
  { "id": "item_82", "name": "Buffing Cap (1X100)", "category": "Other Essentials", "categoryCode": "H", "uom": "/PKT", "netPrice": 80.0 },
  { "id": "item_83", "name": "Printer Roll (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 63.72 },
  { "id": "item_84", "name": "Carry Bag Small (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_85", "name": "Carry Bag Medium (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 17.94 },
  { "id": "item_86", "name": "Carry Bag Large (1X50)", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_87", "name": "Suma Grill", "category": "Other Essentials", "categoryCode": "H", "uom": "/NOS", "netPrice": 1652.0 },
  { "id": "item_88", "name": "Drink 250 ml (1X28)", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 17.14 },
  { "id": "item_89", "name": "Red Bull 250 ml (1X6)", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 99.0 },
  { "id": "item_90", "name": "Coolberg 330 ml (1X24)", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_91", "name": "Monster 300 ml (1X24)", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_92", "name": "Can 300 ml (1X24) 40Rs.", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_93", "name": "Can 300 ml (1X24) 70Rs.", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 0.0 },
  { "id": "item_94", "name": "Water 1 Ltr (1X12)", "category": "Beverages", "categoryCode": "I", "uom": "/NOS", "netPrice": 12.0 }
];